#dockarized jenkins for CICD to build &merge code and result package [CI] to deploy it in tomcat [CD]
version: '3.2'
services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw
      - ./war:/mnt/:rw   #war is shared dir
    ports:
      - 8080:8080
    container_name: jenkins
  
  tomcat:
    image: tomcat
    ports:
      - 7777:8080
    container_name: tomcat
    depends_on:
      - jenkins
    volumes:
      - ./war/:/usr/local/tomcat/webapps    #war is shared dir
