version: '3.2'
services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw
      - ./war:/mnt/:rw
    ports:
      - 8080:8080
    container_name: jenkins
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 3G
        reservations:
          cpus: 0.1
          memory: 1G
  
  tomcat:
    image: tomcat
    ports:
      - 7777:8080
    container_name: tomcat
    depends_on:
      - jenkins
    volumes:
      - ./war/:/usr/local/tomcat/webapps
    deploy:
      resources:
        limits:
          limits:
          cpus: 0.5
          memory: 1G
        reservations:
          cpus: 0.1
          memory: 500M
